PatoCore/FirstCodee/Controllers/AdminAboutController.cs
using BusinessLayer.Concrete;
using BusinessLayer.ValidationRules;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using FluentValidation.Results;
using Microsoft.AspNetCore.Mvc;

namespace FirstCodee.Controllers
{
    public class AdminAboutController : Controller
    {
        AboutManager _aboutManager = new AboutManager(new EFAboutDal());

        [HttpGet]
        public IActionResult Index()
        {
            var value = _aboutManager.TGetById(1);
            return View(value);
        }

        [HttpPost]
        public IActionResult Index(About p)
        {
            AboutValidator av = new AboutValidator();
            ValidationResult result = av.Validate(p);
            if (result.IsValid)
            {
                if (p.Image != null)
                {
                    var extension = Path.GetExtension(p.Image.FileName);
                    var newImageName = Guid.NewGuid() + extension;
                    var location = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/img/", newImageName);

                    using (var stream = new FileStream(location, FileMode.Create))
                    {
                        p.Image.CopyTo(stream);
                    }

                    p.AboutImage = newImageName;
                }
                
                _aboutManager.TUpdate(p);// Yeni resim adı
            }
            else
            {
                foreach (var item in result.Errors)
                {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                }
            }
            return View(p);
        }
    }
}

PatoCore/FirstCodee/Views/AdminAbout/Index.cshtml
@model EntityLayer.Concrete.About
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="container-xxl flex-grow-1 container-p-y">
    <div class="row">
        <div class="col-lg-8 mb-4 order-0 mx-auto">
            <div class="card">
                <div class="d-flex align-items-end row">
                    <div class="col-sm-12">
                        <div class="card-body">
                            <h5 class="card-title text-primary">Hakkımızda Sayfası 🎉</h5>
                            <p class="mb-4">

                            </p>
                            <form asp-action="Index" asp-controller="AdminAbout" method="post" enctype="multipart/form-data">
                                <div class="form-group">
                                </div>
                                <input asp-for="ID" hidden type="text" class="form-control" id="defaultFormControlInput" placeholder="John Doe" aridescribedby="defaultFormControlHelp">

                                <div class="form-group mb-3">
                                    <label for="defaultFormControlInput" class="form-control-label">Hakkımızda Başlık</label>
                                    <input asp-for="Title" type="text" class="form-control" id="defaultFormControlInput" aridescribedby="defaultFormControlHelp">
                                    <div class="text-danger text-sm ms-2">
                                        @Html.ValidationMessageFor(x => x.Title)
                                    </div>
                                </div>


                                <div class="form-group mb-3">
                                    <label for="example-text-input" class="form-control-label">Resim</label>
                                    <input asp-for="AboutImage" class="form-control" type="text" value="@Model.AboutImage" readonly>
                                    <input asp-for="Image" class="form-control" type="file" value="">
                                </div>

                                <div class="form-group mb-3">
                                    <label for="defaultFormControlInput" class="form-control-label">Hakkımızda Açıklama</label>
                                    <textarea id="aboutDesc" rows="10" cols="50" asp-for="Description" class="form-control" type="text" value=""></textarea>
                                    <div class="text-danger text-sm ms-2">
                                        @Html.ValidationMessageFor(x => x.Description)
                                    </div>
                                </div>

                              

                                <button type="submit" class="btn btn-primary">Bilgileri Kaydet</button>
                            </form>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>

</div>