PatoCore/FirstCodee/Controllers/AdminGalleryCategoryController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using Microsoft.AspNetCore.Mvc;

namespace FirstCodee.Controllers
{
    public class AdminGalleryCategoryController : Controller
    {
        GalleryCategoryManager _manager = new GalleryCategoryManager(new EFGalleryCategoryDal());
        public IActionResult Index()
        {
            var values = _manager.TGetlist();
            return View(values);
        }
        [HttpGet]
        public IActionResult add()
        {
            return View();
        }
        [HttpPost]
        public IActionResult add(GalleryCategory p)
        {
            p.State = true;
            _manager.TAdd(p);
            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult update(int id)
        {
            var value = _manager.TGetById(id);
            return View(value);
        }
        [HttpPost]
        public IActionResult update(GalleryCategory p)
        {
            _manager.TUpdate(p);
            return RedirectToAction("Index");
        }
        public IActionResult delete(int id)
        {
            var value = _manager.TGetById(id);
            _manager.TDelete(value);
            return RedirectToAction("Index");
        }
    }
}

PatoCore/FirstCodee/Views/AdminGalleryCategory/Index.cshtml
@using EntityLayer.Concrete
@model List<GalleryCategory>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="container-xxl flex-grow-1 container-p-y">
    <div class="row">
        <div class="col-lg-10 mb-4 order-0 mx-auto">
            <div class="card">
                <div class="d-flex align-items-end row">
                    <div class="col-sm-12">
                        <div class="card">
                            <div class="row">
                                <div class="col-6">
                                    <h5 class="card-header">Galeri Kategori Listesi</h5>
                                </div>
                                <div class="col-6 d-flex justify-content-end align-items-center">
                                    <a href="/AdminGalleryCategory/add/" class="btn btn-primary">
                                        + Yeni Kategori Ekle
                                    </a>
                                </div>
                            </div>
                            <div class="table-responsive text-nowrap" style="height:75vh">
                                <table class="table">
                                    <thead>
                                        <tr>
                                            <th>Galeri Kategori Başlığı</th>
                                            <th>Durum</th>
                                            <th class="text-end">İşlemler</th>
                                        </tr>
                                    </thead>
                                    <tbody class="table-border-bottom-0">
                                        @foreach (var item in Model)
                                        {
                                            <tr>
                                                <td><i class="fab fa-angular fa-lg text-danger me-3"></i> <strong>@item.Title</strong></td>

                                                @if (item.State == true)
                                                {
                                                    <td><span class="badge bg-label-primary me-1">Aktif</span></td>
                                                }
                                                else if (item.State == false)
                                                {
                                                    <td><span class="badge bg-label-danger me-1">Pasif</span></td>
                                                }
                                                <td>
                                                    <div class="dropdown text-end">
                                                        <button type="button" class="btn p-0 dropdown-toggle hide-arrow" data-bs-toggle="dropdown">
                                                            <i class="bx bx-dots-vertical-rounded"></i>
                                                        </button>
                                                        <div class="dropdown-menu">
                                                            <a class="dropdown-item" href="/AdminGalleryCategory/update/@item.ID"><i class="bx bx-edit-alt me-1"></i> Düzenle</a>
                                                            <a class="dropdown-item" href="/AdminGalleryCategory/delete/@item.ID"><i class="bx bx-trash me-1"></i> Sil</a>
                                                        </div>
                                                    </div>
                                                </td>
                                            </tr>
                                        }


                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>

PatoCore/FirstCodee/Views/AdminGalleryCategory/add.cshtml
@model EntityLayer.Concrete.GalleryCategory
@{
    ViewData["Title"] = "add";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="container-xxl flex-grow-1 container-p-y">
    <div class="row">
        <div class="col-lg-6 mb-4 order-0 mx-auto">
            <div class="card">
                <div class="d-flex align-items-end row">
                    <div class="col-sm-12">
                        <div class="card-body">
                            <h5 class="card-title text-primary">Kategori Ekleme Sayfası 🎉</h5>
                            <p class="mb-4">

                            </p>
                            <form asp-action="add" asp-controller="AdminGalleryCategory" method="post">
                                <div class="form-group">
                                </div>

                                <div class="form-group mb-3">
                                    <label for="defaultFormControlInput" class="form-control-label">Kategori Adı</label>
                                    <input asp-for="Title" type="text" class="form-control" id="defaultFormControlInput" aridescribedby="defaultFormControlHelp">
                                    <div class="text-danger text-sm ms-2">
                                        @Html.ValidationMessageFor(x => x.Title)
                                    </div>
                                </div>

                                <button type="submit" class="btn btn-primary">Bilgileri Kaydet</button>
                            </form>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>

</div>

PatoCore/FirstCodee/Views/AdminGalleryCategory/update.cshtml
@model EntityLayer.Concrete.GalleryCategory
@{
    ViewData["Title"] = "update";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


<div class="container-xxl flex-grow-1 container-p-y">
    <div class="row">
        <div class="col-lg-6 mb-4 order-0 mx-auto">
            <div class="card">
                <div class="d-flex align-items-end row">
                    <div class="col-sm-12">
                        <div class="card-body">
                            <h5 class="card-title text-primary">Galeri Kategori Düzenleme Sayfası 🎉</h5>
                            <p class="mb-4">

                            </p>
                            <form asp-action="update" asp-controller="AdminGalleryCategory" method="post">
                                <div class="form-group">
                                    <input asp-for="ID" type="text" class="form-control" id="defaultFormControlInput" aridescribedby="defaultFormControlHelp" hidden>
                                </div>

                                <div class="form-group mb-3">
                                    <label for="defaultFormControlInput" class="form-control-label">Kategori Adı</label>
                                    <input asp-for="Title" type="text" class="form-control" id="defaultFormControlInput" aridescribedby="defaultFormControlHelp">
                                    <div class="text-danger text-sm ms-2">
                                        @Html.ValidationMessageFor(x => x.Title)
                                    </div>
                                </div>

                                <div class="form-group mb-3">
                                    <label for="stateSelect" class="form-label">Durum</label>
                                    <select asp-for="State" class="form-select">
                                        <option value="true">Aktif</option>
                                        <option value="false">Pasif</option>
                                    </select>
                                </div>

                                <button type="submit" class="btn btn-primary">Bilgileri Kaydet</button>
                            </form>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>

</div>